---

- hosts: k3s
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: perf

- hosts: k3s:!edge
  become: yes
  roles:
    - role: k3s/master

- hosts: k3s:!cloud
  become: yes
  roles:
    - role: k3s/node
